services:
  app:
    build:
      context: ./app/
      args:
        - POETRY_VERSION=1.8.4
        - POETRY_VIRTUALENVS_IN_PROJECT=1
        - POETRY_NO_INTERACTION=1
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
